### ISSUE TITLE
'Compiling a test with HDF5 failed; hdf5.h cannot be found'

### ISSUE THREAD

**Issue by NestorCerpa** [fretif/pagure#20]
Machine : _Linux newsubmap 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux_

After installing cmake (3.20.5), zlib (1.2.11) and hdf5 (1.10.5) I wanted to install netcdf (4.8.0) but during the checking process, pagure throws an error 'Compiling a test with HDF5 failed'. See below the .log

[pagure.log](https://github.com/fretif/pagure/files/10570384/pagure.log)

**Comment by fretif** [comment]
Thanks Nestor for the reporting this issue. It was a wrong include in the compilation arguments. I fixed it in a new commit
